### PR TITLE
Add a TODO Doc for the CTT Optimizer.

### PR DESCRIPTION
**Pull request by levi-chavez**
I was told to do this by Couleur as we are working on an optimizer.

### CODE REVIEW

**Comment by couleurm** [comment]
Thanks for writing this, anyone else seeing this feel free to comment here with what you'd like to add

I don't think I'll allow Defender modifications, though I could link he3al's Defender disabler for the ones with determination

It'll either be made as a series of Apply/Skip prompts or a GUI with tickboxes

Edit: yes i will make tweakfuncs to get JREs and maybe re take on Moony

**Comment by couleurm** [comment]
he3als notes, and my thoughts about them in italic

1) msi mode for all devices that support it - _it may be worse on some devices, cant find what ppl said about it on ctt_
2) disabling not needed devices (that can be safely disabled) _how does that help performance in any way_
3) disabling power saving (for desktop, could include a power plan ig)
4) drivers and services (disabling safe-to-disable drivers/services only) _does services REALLY matter if they never ever run or if they do take 0% CPU and a few regs'a ram?_
5) enabling HAGS if it's supported (hardware accelerated gpu scheduling) _Sophia got a func for that👍_
6) data queue sizes (not sure if this really effects latency, someone should test it) _Would appreciate testing_
7) disabling mitigations (dmaremapping, CFG, etc) _I'm not _
8) mmcss tweaks _appreciate testing as well_
9) disabling gamebar 👍
10) win32 priority seperation _as well_
11) auto configurating window animations (disabling them) _probably only impactful on bad PCs_
12) bcdedit settings - not sure about this tho, could be dependant on the system _as well. . . .._
13) networking _prove me any of the adapter settings matter first :bruhtent:_

**Comment by levi-chavez** [comment]
1. MSI Mode isn't very useful anymore, and it can perform bad on low end hardware. (i have experience with this in versions 1607-20H2 and it fucks up performance really badly on low end ATI/amd gpus.

2. Disabling Devices doesn't affect much if they are coded well. If it is an driver or device used in old versions of windows, then you should remove it.

3. For 3, just use a powerplan like high performance. It literally does that for most devices such as PCIe and hard drives. That comment was useless.

4. Reducing services have an impact on latency and FPS on low end hardware due to either a bad CPU or slow hard drive.

5. Hardware accel gpu sched isn't supported on anything 900 series below on the nvidia side, and anything rx 400/4000 series or below on team red. (it may be the wrong models, but the idea still applies) This needs to be applicable to all hardware. Also its for DX11/DX12. Not worth it in my opinion.

6. Data queue sizes have been proven to... not affect shit!

8. mmccss may or may affect performance, it 100% does not in many mainstream games and can cause issues, I am personally going to not deal with that.

**Comment by couleurm** [comment]
@dotslashlevi he3als also replied

1) idk which devices msi mode would be worse on, if the device is supported... https://en.wikipedia.org/wiki/Message_Signaled_Interrupts#Advantages
2) reduces the amount of unnecessary interrupts
4) whilst this is mostly true, some services can use resources in the background https://github.com/djdallmann/GamingPCSetup/blob/master/CONTENT/DOCS/SERVICES/README.md
6) i don't have any latency testing devices, would be good if someone else could do it tho
7) it would be nice to have an option, it doesn't have to be automated. especially with older cpus, mitigations can worsen performance significantly
8) probably won't effect much, would be a little nice tweak though https://github.com/djdallmann/GamingPCSetup/blob/master/CONTENT/RESEARCH/WINSERVICES/README.md
10) there has been testing done by spddl for win32prorityseperation https://docs.google.com/spreadsheets/d/1ZWQFycOWdODkUOuYZCxm5lTp08V2m7gjZQSCjywAsl8/edit#gid=762933934
11) this is more QoL
12) bcdedit settings can be a bit of a grey area, there should probably be quite a lot of research into each tweak before applying anything
13) probably won't help too much, but you can look here for some good tweaks https://github.com/djdallmann/GamingPCSetup/blob/master/CONTENT/DOCS/NETWORK/README.md (really though, it's not that significant)

**Comment by levi-chavez** [comment]
Alright, so MSI mode is not supported on all devices obviously. That ATI GPU was an Apple ATI 6750M, which had eDPI graphics and was super slow. I would say anything pre 2011-2012, especially all in ones, do not react well to MSI mode.

Also, most of the tweaks are studied by [GGOS](https://discord.gg/ggos), their discord has events where they say if a tweak affects the system or not and people react to the discord message.

Win32Priority Separation literally makes your game feel completely different when comparing 26 variable short to 14 variable long. 26 variable short has low latency and is default in older windows versions. (7, 8, 10) 18 fixed long and anything from 14-16 variable long are used in newer windows versions. (such as 11+) The fixed long and 14 variable long on my lower end hardware has the best fps out of all of them, I have gotten 700 frames on forge on terrible hardware using variable long 14. 18 variable long gives me 400-500 frames, and 26 variable short gives me 200-300 fps. I use 18 fixed short because it has semi low mouse delay and gives a good amount of fps.

Next up: services. The less services that are in the background on low-mid end cpus, the better the mouse/latency reaction speed and latency are. 100% feel a difference between 160 processes on 75 hz and 40-60 proccesses on 75hz, even 60hz feels better than 160 on 75hz sometimes.

Networking: most of the tweaks are placebo. If you set a good dscp value for your specific router when no one is on the network, nothing is going to change. If you change adapter settings, they usually change the amount of cpu used. I usually disable most settings and put the options on a 2nd core/thread for better performance and call it quits. I have used [these](https://github.com/djdallmann/GamingPCSetup/blob/master/CONTENT/DOCS/NETWORK/README.md) settings before so I already knew about them. I found them from he3als or you - depending on who is reading this.

BCDEdit settings may or may not help, depends if the default hardware clock is set low. if its not, or you can't change it, then theres no point in disabling platform tick. I personally might remove the BCDEdit settings. I don't feel much of a difference, but I'm on something with locked down firmware anyways. (its an old mac smh)

I'm going to be honest, I don't disable many devices in dev manager. But, if it helps with reduce latency and random interrupts, then we should 100% change those, thanks for the tip.

Migitations can be disabled if needed, I have heard it takes a toll on older cpus, so yeah we could disable them.

**Comment by couleurm** [comment]
> Win32Priority Separation literally makes your game feel completely different [...] have gotten 700 frames on forge on terrible hardware using variable long 14. 18 variable long gives me 400-500 frames, and 26 variable short gives me 200-300 fps. I use 18 fixed short because it has semi low mouse delay and gives a good amount of fps.

benchmarking needed 👍

> Also, most of the tweaks are studied by [GGOS](https://discord.gg/ggos), their discord has events where they say if a tweak affects the system or not and people react to the discord message.

what channel is it

> Next up: services. The less services that are in the background on low-mid end cpus, the better the mouse/latency 

I mean if they are clearly label on what depends on them I'd be positive to make a tweakfunc that prompts the for each, and what each service break

> Migitations can be disabled

I'd only say it's worth risking if you were on a dedicated windows install with only your games logged, but not for a main install with stuff you don't want shared/ransommed

**Comment by levi-chavez** [comment]
I will do some benchmarking using software for the win32priority separation.

I forgot what channel it was.

A tweakfunc that would prompt for certain services is good.

Migitations shouldn't be disabled on pc a that downloads many zip and exe files so I wouldn't want them to be off for those who web browse a lot.

**Comment by levi-chavez** [comment]
10 days ago, yikes. Anyways, I had to reinstall Linux because I broke my install by installing custom coreutils which caused pacman to not build and install the kernel correctly. Therefore I lost the data on my windows VM. (albeit not a lot)

**Comment by levi-chavez** [comment]
It just makes me want to start this again due to fact that im gonna be building an iso and installing a fresh, legit, and bloated copy of windows. I might be able to do some basic UI and commands that run the tweaks. Obviously they will be better than TweakMC, its ui is ugly.

**Comment by couleurm** [comment]
Moved to the [Projects](https://github.com/couleur-tweak-tips/TweakList/projects)

**Pull request closed without merging**
