### PR TITLE
Update Install-NVCPL.ps1 script and add New-Buffer.ps1 to Helpers.

### PR DESCRIPTION
**Pull request by Aetopia**
1. `Install-NVCPL.ps1` has been updated to directly invoked the script from the source repository since minor patches can be pushed without the need of creating pull requests for TweakList.
2. `New-Buffer.ps1` allows for the creation of Alternative Buffers, very useful if you want to clear the console screen but without using `Clear-Host`.
3. Add Alternative Buffer support for the Menu Helper function.
4. Add a function to get all PCI devices that support MSI Mode.

### CODE REVIEW

**Comment by couleurm** [comment]
image
could you explain that

**Comment by Aetopia** [comment]
> image could you explain that

I am always constantly updating my Install-NVCPL script and I don't want to always do a pull request for that project since its updation rate is way to frequent hence why I am simply directly invoking the script from this repo: https://github.com/aetopia/install-nvcpl which has the updated version.

**Comment by couleurm** [comment]
Why move it outside of Aetopia's utils???

**Comment by couleurm** [comment]
can you please tell me why you need two Install-NVCPL? And why you'd even need it outside of `Aetopia utils`...? please communicate

**Comment by Aetopia** [comment]
> 

I may have created that other one by mistake, I will remove it.

**Comment by Aetopia** [comment]
Updated Install-ZetaLoader to support Halo Infinite Season 4.

**Comment by couleurm** [comment]
could you revert your changes to Menu.ps1 or if they are intended explain what you modified

**Comment by Aetopia** [comment]
> could you revert your changes to Menu.ps1 or if they are intended explain what you modified

Adds the ability to display a menu in an alternative buffer, this can be toggled by passing `-AlternativeBuffer`, also nothing has been changed the code aside from this functionality, the code was just formatted (styled).

**Comment by couleurm** [comment]
Cleaning old prs

**Pull request closed without merging**
